app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

app_contacto:
    resource: "@AppBundle/Resources/config/routing/contacto.yml"
    prefix: /contacto

app_testdrive:
    resource: "@AppBundle/Resources/config/routing/testdrive.yml"
    prefix: /testdrive